set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set relativenumber
set number
set signcolumn=yes
set hidden
set noswapfile
set backupcopy=yes
set termguicolors
set updatetime=50
set nowrap
set completeopt=menuone,preview,noinsert,noselect
set timeoutlen=300
set splitbelow
set scrolloff=8
set laststatus=3
set magic
